FROM node As Builder

WORKDIR /app

COPY package.json /app/package.json

RUN npm install
RUN npm install -g @angular/cli@

COPY . /app

RUN ng build --prod

FROM nginx

COPY --from=Builder /app/dist/burger /usr/share/nginx/html
